### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by entropitor** [nix-community/comma#1]
Hi

I'm new to nix, it would be nice to have a oneliner on how to install this nix package for newcomers like me 😅 I already have nix installed

EDIT: I figured out you can install it using `nix-env -i -f https://github.com/Shopify/comma/tarball/master`

**Comment by jeffutter** [comment]
Also new to nix here so this could be wrong... but if you are using home-manager this seems to work:

```nix
{ config, pkgs, ... }:

let
  comma = import ( pkgs.fetchFromGitHub {
      owner = "Shopify";
      repo = "comma";
      rev = "4a62ec17e20ce0e738a8e5126b4298a73903b468";
      sha256 = "0n5a3rnv9qnnsrl76kpi6dmaxmwj1mpdd2g0b4n1wfimqfaz6gi1";
  }) {};

in

{
  home.packages = with pkgs; [
    comma
  ];
}
```

**Comment by Artturin** [comment]
i have added instructions to the readme
