### ISSUE TITLE
Always depends on full nixpkgs checkout

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/comma#14]
Since flake support  comma now always depends on the full nixpkgs source which needs to be copied to remote builders when building it. This is really unnecessary when you handle nix-index standalone. How can I avoid this? Is there an easy way to get an option into the flake to build it without any updater support?

Because of pkgs.path my home-manager generation is now about 1GB bigger than before.

```ShellSession
$ nix store diff-closures /nix/var/nix/profiles/per-user/hotpi/home-manager-5-link /nix/var/nix/profiles/per-user/hotpi/home-manager-6-link/
nixpkgs: ∅ → ε, +1099148.6 KiB
source: -49.9 KiB
```

**Comment by Mic92** [comment]
What if the default NIX_PATH would passed as a parameter to the nix expression by specifying `path` in the attribute list?
And than if this expression is called  `path = null` or empty string the expression would not add nixpkgs as a dependency?

**Comment by Artturin** [comment]
https://github.com/nix-community/comma/pull/18
