### ISSUE TITLE
Use local `nixpkgs` instead of downloading it as soon as a new "version" is available

### ISSUE THREAD

**Issue by aaschmid** [nix-community/comma#15]
As far as I could analyze the used `nix shell` if `nix` v2.4 or above downloads `nixpkgs` once a new "version" is available. I am unsure why this is the case. 

I have not found a proper solution staying with `nix shell` however could think about a fix using `nix-shell` like [here](https://github.com/aaschmid/comma/tree/fix.nixpkgs.download.by.nix.shell). Even though this does not allow me specifying `$NIXPKGS`. Was this only introduced for flakes and therefore only relevant there?

Is the reason for this default behavior of `nix` (at least I interpret it like that) because of compatibility with binary caches? Are is there any other reason which I haven't found in documentation?

I think this could be a worthwhile improvement because local `nixpkgs` might be sufficient to run any new scripts and it saves a lot of time as updates to `nixpkgs` are not very rare ;-)

Any opinion welcome!

**Comment by SuperSandro2000** [comment]
#14

**Comment by aaschmid** [comment]
I think this is not related to #14 @SuperSandro2000 because it is already part of v1.1.0 introduced by commit f6f259214b1b00e18dd14f5a66d65b06842e6349 by using `nix shell` instead of `nix run` with `nix` v2.4.

**Comment by aaschmid** [comment]
For me the fix in https://github.com/nix-community/comma/commit/9602aa4e34f53c8a286376026aa4c967f8975d13 work properly.

**Comment by Artturin** [comment]
fixed in https://github.com/nix-community/comma/commit/2d5ddcbf5a1071ba3d31148fbef8ffe127eebcdd

specifically https://github.com/nix-community/comma/blob/0b4e4bc525eda78bcb576601d087db1775a00ebc/src/main.rs#L102-L106

so first the channel is used and if that does not exist then the flake registry is used
