### ISSUE TITLE
Add to Nixpkgs

### ISSUE THREAD

**Issue by samuela** [nix-community/comma#2]
Is there any way we could get this added to Nixpkgs? Doing so would greatly simplify the installation/setup/upgrade process.

**Comment by Xe** [comment]
I added comma to my [NUR](https://github.com/nix-community/NUR) repo [nur.repos.xe](https://github.com/Xe/xepkgs). You can install it by adding it to your `configuration.nix` with:

```nix
{
  nixpkgs.config.packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };

  environment.systemPackages = [ pkgs.nur.repos.xe.comma ];
}
```

Or in a user account by adding this to your `~/.config/nixpkgs/config.nix`:

```nix
{
  packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };
}
```

And then running `nix-env -iA nixpkgs.nur.repos.xe.comma`. Either way should let you install/update this software without much issue.

**Comment by fzakaria** [comment]
This tool is great.
Yea why isn't it on nixpkgs ?

**Comment by workflow** [comment]
Looks like this can be closed :)
