### ISSUE TITLE
No Longer Working - Only Shows `no match`

### ISSUE THREAD

**Issue by poita66** [nix-community/comma#23]
I installed comma in my home-manager config and it's been working well for a while, and has been awesome!

However recently all it tells me is `no match`, even when I execute `, cowsay neato`

As this is using the pre-built nix-index-database, I'm not sure how to attempt to update the index, or even if that'd help.

Version: 1.2.3 (from the unstable channel)
OS: NixOS 21.11
Arch: x86_64

Any help would be greatly appreciated!

**Comment by Artturin** [comment]
we no longer bundle the index so you'll need to download it manually from https://github.com/Mic92/nix-index-database

**Comment by poita66** [comment]
Ah OK, thanks. We should add that to the README

For anyone else who reads this, you'll need to run the following (sourced from https://github.com/Mic92/nix-index-database README) to download/update the database:
```
(
  filename="index-x86_64-$(uname | tr A-Z a-z)"
  mkdir -p ~/.cache/nix-index
  cd ~/.cache/nix-index
  # -N will only download a new version if there is an update.
  wget -q -N https://github.com/Mic92/nix-index-database/releases/latest/download/$filename
  ln -f $filename files
)
```
