### ISSUE TITLE
Print package name of executable

### ISSUE THREAD

**Issue by jooooscha** [nix-community/comma#38]
Hi,
would it be possible to add a flag like `--package` that causes comma to print the package name (plus maybe other information) instead of executing the program.

This would be useful when you know the name of the executable, but the nix package is named differently. For example, the neovim binary is called `nvim`. Let's say I do not know that the project/package is actually called neovim. Now, I could only use comma to run neovim (`, nvim`) but I would have a hard time to install neovim. With a `--package` flag I could find out that the package is actually called neovim.

Thanks :)

**Comment by Artturin** [comment]
Fixed by https://github.com/nix-community/comma/commit/34ba5a05bcfd13cf8b1776ff2a2a8068adb45d07
