### ISSUE TITLE
Provide an environment variable to specify the nix-index database location

### ISSUE THREAD

**Issue by Mic92** [nix-community/comma#50]
I am currently trying to use XDG_CACHE_DIR but this also affects other application that try to write to a read-only directory: https://github.com/Mic92/nix-index-database/issues/48

**Comment by Mic92** [comment]
nix-index has the following flake that could be used:

```
-d, --db <DATABASE>      Directory where the index is stored [default: /home/joerg/.cache/nix-index/]
```

**Comment by Artturin** [comment]
Fixed by https://github.com/nix-community/nix-index/pull/213
