### ISSUE TITLE
Cannot see which packages contain matching executable without running anything

### ISSUE THREAD

**Issue by stelcodes** [nix-community/comma#72]
I frequently check which packages include an executable but I don't want to run the command. Comma shows me what packages contain the executable with `fzy` in the selector but then I have to send a SIGINT to exit. If there's only package, the command will just run. `--print-package` only prints the package containing the one chosen executable and runs the command afterward.

What if there was another flag like `--list-packages` that printed off each package containing the executable and exited immediately after?

**Comment by Artturin** [comment]
Just use `nix-locate` instead `nix-locate -w --top-level  -- "/bin/hello"`

**Comment by Artturin** [comment]
Anyways https://github.com/nix-community/comma/pull/79
