### ISSUE TITLE
Cache package per executable

### ISSUE THREAD

**Issue by diniamo** [nix-community/comma#77]
I'll probably implement this myself, I'm making an issue so I don't forget. It's probably also a good practice or something. Suggestions on what other features there should be are welcome.

Features:
- [ ] Cache the package used per executable (this avoids both the nix-index lookup and the selection menu)
- [ ] Add a flag to empty the cache / remove a specific executable

**Comment by jooooscha** [comment]
Just as a side note; maybe it helps someone until this is implemented.
I just wrapped a shell script around comma that reads the package with `--print-package` and then starts a `nix shell` with that.

This has the advantage, that I don't have to know the binary name (which is not always the same as the package), and I can rerun the binary without any delay, until I exit the `nix shell`

**Comment by Artturin** [comment]
> Just as a side note; maybe it helps someone until this is implemented. I just wrapped a shell script around comma that reads the package with `--print-package` and then starts a `nix shell` with that.

https://github.com/nix-community/comma/pull/79
