### ISSUE TITLE
Doesn't work with shells

### ISSUE THREAD

**Issue by walseb** [nix-community/comma#8]
This package doesn't work on shells like `eshell` and `shell` in emacs. And it probably doesn't work on any other shells either. This is probably due to the prompt that pops up when you have to choose which package to get the requested command from. It sort of works in emacs `shell` but I can't actually make a choice

**Comment by Artturin** [comment]
if you have any fuzzy picker that works in emacs you can make comma use it by setting the `COMMA_PICKER` variable
