### ISSUE TITLE
Add support for graphical pickers like fuzzel

### ISSUE THREAD

**Issue by arjan-s** [nix-community/comma#89]
I'd love to make a zenity-based input dialog that can be called from a graphical menu, which calls comma which pops up fuzzel (or other dmenu-like picker) in case multiple matches are found.

**Comment by Jeidnx** [comment]
You can configure which picker to use with the `-p` or `--picker` flag. For fuzzel a simple script calling `fuzzel --dmenu` works.

**Comment by Artturin** [comment]
Yeah I don't think we need to do anything
