### ISSUE TITLE
Support linking to gcroots?

### ISSUE THREAD

**Issue by FBIGlowie** [nix-community/comma#93]
Hello, are there plants to implement system where kinda like [nix-direnv](https://github.com/nix-community/nix-direnv)'s feature of linking to gcroots so garbage collection doesn't wash "important" packages away?

If not, where can I start looking if I wanted to contrib to such a feature?

Thanks,
Sapi

**Comment by Artturin** [comment]
Why not just add the package to your configuration if you use it often enough to need this feature.

**Comment by FBIGlowie** [comment]
> Why not just add the package to your configuration if you use it often enough to need this feature.

Thats fair ig
