### ISSUE TITLE
No executable `dbeaver-bin` found in nix-index database.

### ISSUE THREAD

**Issue by cheirekov** [nix-community/comma#94]
I am trying to start dbeaver
i have it in nix-index nix-locate dbeaver 
....
dbeaver-bin.out                                  16,040 x /nix/store/jji2nzc2diqwaffj1lf6si6lryki4brv-dbeaver-bin-24.3.0/bin/dbeaver
...
But when i am trying to start it like
, dbeaver-bin
or
, dbeaver
I have 
No executable `dbeaver-bin` found in nix-index database.

Please advice

**Comment by SuperSandro2000** [comment]
You are not using nix-index-database by any chance? That has it's own index in the store.

Also trying to run dbeaver-bin won't work as the file is named dbeaver

**Comment by cheirekov** [comment]
Thank you for your fast response !!! 
Here is my set:
Ubuntu 24.04
nix (Nix) 2.24.9
home-manager - 25.05-pre
Standard flake home-manager config - (nix-index-database.hmModules.nix-index)
home.nix:
...
  programs.nix-index.enable = true;
  programs.nix-index-database.comma.enable = true;
...
Update:
after ran nix-shell -p dbeaver-bin.out --run dbeaver 
now i can run it with , dbeaver

Thank You for your support !
What about packages like anydesk they are not in the index but still in packages ?

**Comment by SuperSandro2000** [comment]
> after ran nix-shell -p dbeaver-bin.out --run dbeaver
> now i can run it with , dbeaver

I don't have an idea how that correlates as it really shouldn't.

> What about packages like anydesk they are not in the index but still in packages ?

Isn't the license of that or a dependency unfree? Then it isn't built done hydra and then we cannot know the paths in it and it is excluded by the index.
